/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SensorSharing"
 * 	found in "SensorSharing.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_DetectedObstacleList_H_
#define	_DetectedObstacleList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DetectedObstacleData;

/* DetectedObstacleList */
typedef struct DetectedObstacleList {
	A_SEQUENCE_OF(struct DetectedObstacleData) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DetectedObstacleList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DetectedObstacleList;
extern asn_SET_OF_specifics_t asn_SPC_DetectedObstacleList_specs_1;
extern asn_TYPE_member_t asn_MBR_DetectedObstacleList_1[1];
extern asn_per_constraints_t asn_PER_type_DetectedObstacleList_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DetectedObstacleData.h"

#endif	/* _DetectedObstacleList_H_ */
#include <asn_internal.h>
