/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Platooning"
 * 	found in "Platooning.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_MemberList_H_
#define	_MemberList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MemberNode;

/* MemberList */
typedef struct MemberList {
	A_SEQUENCE_OF(struct MemberNode) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MemberList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MemberList;
extern asn_SET_OF_specifics_t asn_SPC_MemberList_specs_1;
extern asn_TYPE_member_t asn_MBR_MemberList_1[1];
extern asn_per_constraints_t asn_PER_type_MemberList_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MemberNode.h"

#endif	/* _MemberList_H_ */
#include <asn_internal.h>
