/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Map"
 * 	found in "Map.asn"
 * 	`asn1c -gen-PER`
 */

#include "MovementEx.h"

asn_TYPE_member_t asn_MBR_MovementEx_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MovementEx, remoteIntersection),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NodeReferenceID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"remoteIntersection"
		},
	{ ATF_POINTER, 2, offsetof(struct MovementEx, phaseId),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PhaseID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"phaseId"
		},
	{ ATF_POINTER, 1, offsetof(struct MovementEx, turn_direction),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Maneuver,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"turn-direction"
		},
};
static const int asn_MAP_MovementEx_oms_1[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_MovementEx_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MovementEx_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* remoteIntersection */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* phaseId */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* turn-direction */
};
asn_SEQUENCE_specifics_t asn_SPC_MovementEx_specs_1 = {
	sizeof(struct MovementEx),
	offsetof(struct MovementEx, _asn_ctx),
	asn_MAP_MovementEx_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_MovementEx_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_MovementEx = {
	"MovementEx",
	"MovementEx",
	&asn_OP_SEQUENCE,
	asn_DEF_MovementEx_tags_1,
	sizeof(asn_DEF_MovementEx_tags_1)
		/sizeof(asn_DEF_MovementEx_tags_1[0]), /* 1 */
	asn_DEF_MovementEx_tags_1,	/* Same as above */
	sizeof(asn_DEF_MovementEx_tags_1)
		/sizeof(asn_DEF_MovementEx_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_MovementEx_1,
	3,	/* Elements count */
	&asn_SPC_MovementEx_specs_1	/* Additional specs */
};

