/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PAM"
 * 	found in "PAM.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_PAMNodeList_H_
#define	_PAMNodeList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PAMNode;

/* PAMNodeList */
typedef struct PAMNodeList {
	A_SEQUENCE_OF(struct PAMNode) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PAMNodeList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PAMNodeList;
extern asn_SET_OF_specifics_t asn_SPC_PAMNodeList_specs_1;
extern asn_TYPE_member_t asn_MBR_PAMNodeList_1[1];
extern asn_per_constraints_t asn_PER_type_PAMNodeList_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PAMNode.h"

#endif	/* _PAMNodeList_H_ */
#include <asn_internal.h>
