/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VIR"
 * 	found in "VIR.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_PathPlanning_H_
#define	_PathPlanning_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PathPlanningPoint;

/* PathPlanning */
typedef struct PathPlanning {
	A_SEQUENCE_OF(struct PathPlanningPoint) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PathPlanning_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PathPlanning;
extern asn_SET_OF_specifics_t asn_SPC_PathPlanning_specs_1;
extern asn_TYPE_member_t asn_MBR_PathPlanning_1[1];
extern asn_per_constraints_t asn_PER_type_PathPlanning_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PathPlanningPoint.h"

#endif	/* _PathPlanning_H_ */
#include <asn_internal.h>
