/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VIR"
 * 	found in "VIR.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_Req_SensorSharing_H_
#define	_Req_SensorSharing_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ReferencePathList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Req-SensorSharing */
typedef struct Req_SensorSharing {
	ReferencePathList_t	 detectArea;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Req_SensorSharing_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Req_SensorSharing;
extern asn_SEQUENCE_specifics_t asn_SPC_Req_SensorSharing_specs_1;
extern asn_TYPE_member_t asn_MBR_Req_SensorSharing_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _Req_SensorSharing_H_ */
#include <asn_internal.h>
