/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VIR"
 * 	found in "VIR.asn"
 * 	`asn1c -gen-PER`
 */

#include "Req-LaneChange.h"

asn_TYPE_member_t asn_MBR_Req_LaneChange_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Req_LaneChange, upstreamNode),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NodeReferenceID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"upstreamNode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Req_LaneChange, downstreamNode),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NodeReferenceID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"downstreamNode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Req_LaneChange, targetLane),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"targetLane"
		},
};
static const ber_tlv_tag_t asn_DEF_Req_LaneChange_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Req_LaneChange_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* upstreamNode */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* downstreamNode */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* targetLane */
};
asn_SEQUENCE_specifics_t asn_SPC_Req_LaneChange_specs_1 = {
	sizeof(struct Req_LaneChange),
	offsetof(struct Req_LaneChange, _asn_ctx),
	asn_MAP_Req_LaneChange_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Req_LaneChange = {
	"Req-LaneChange",
	"Req-LaneChange",
	&asn_OP_SEQUENCE,
	asn_DEF_Req_LaneChange_tags_1,
	sizeof(asn_DEF_Req_LaneChange_tags_1)
		/sizeof(asn_DEF_Req_LaneChange_tags_1[0]), /* 1 */
	asn_DEF_Req_LaneChange_tags_1,	/* Same as above */
	sizeof(asn_DEF_Req_LaneChange_tags_1)
		/sizeof(asn_DEF_Req_LaneChange_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Req_LaneChange_1,
	3,	/* Elements count */
	&asn_SPC_Req_LaneChange_specs_1	/* Additional specs */
};

