/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VIR"
 * 	found in "VIR.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_ReqInfo_H_
#define	_ReqInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Req-LaneChange.h"
#include "Req-ClearTheWay.h"
#include "Req-SignalPriority.h"
#include "Req-SensorSharing.h"
#include "Req-ParkingArea.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ReqInfo_PR {
	ReqInfo_PR_NOTHING,	/* No components present */
	ReqInfo_PR_laneChange,
	ReqInfo_PR_clearTheWay,
	ReqInfo_PR_signalPriority,
	ReqInfo_PR_sensorSharing,
	ReqInfo_PR_parking
	/* Extensions may appear below */
	
} ReqInfo_PR;

/* ReqInfo */
typedef struct ReqInfo {
	ReqInfo_PR present;
	union ReqInfo_u {
		Req_LaneChange_t	 laneChange;
		Req_ClearTheWay_t	 clearTheWay;
		Req_SignalPriority_t	 signalPriority;
		Req_SensorSharing_t	 sensorSharing;
		Req_ParkingArea_t	 parking;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReqInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReqInfo;
extern asn_CHOICE_specifics_t asn_SPC_ReqInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_ReqInfo_1[5];
extern asn_per_constraints_t asn_PER_type_ReqInfo_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ReqInfo_H_ */
#include <asn_internal.h>
