/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSC"
 * 	found in "RSC.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_RoadsideCoordination_H_
#define	_RoadsideCoordination_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MsgCount.h"
#include <OCTET_STRING.h>
#include "DSecond.h"
#include "Position3D.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VehicleCoordination;
struct LaneCoordination;

/* RoadsideCoordination */
typedef struct RoadsideCoordination {
	MsgCount_t	 msgCnt;
	OCTET_STRING_t	 id;
	DSecond_t	 secMark;
	Position3D_t	 refPos;
	struct coordinates {
		A_SEQUENCE_OF(struct VehicleCoordination) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *coordinates;
	struct laneCoordinates {
		A_SEQUENCE_OF(struct LaneCoordination) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *laneCoordinates;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RoadsideCoordination_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RoadsideCoordination;
extern asn_SEQUENCE_specifics_t asn_SPC_RoadsideCoordination_specs_1;
extern asn_TYPE_member_t asn_MBR_RoadsideCoordination_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VehicleCoordination.h"
#include "LaneCoordination.h"

#endif	/* _RoadsideCoordination_H_ */
#include <asn_internal.h>
