/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PSM"
 * 	found in "PSM.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_RoadWorkerExtensions_H_
#define	_RoadWorkerExtensions_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RoadWorkerType.h"
#include "RoadWorkerActivityType.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RoadWorkerExtensions */
typedef struct RoadWorkerExtensions {
	RoadWorkerType_t	*workerType	/* OPTIONAL */;
	RoadWorkerActivityType_t	*activityType	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RoadWorkerExtensions_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RoadWorkerExtensions;
extern asn_SEQUENCE_specifics_t asn_SPC_RoadWorkerExtensions_specs_1;
extern asn_TYPE_member_t asn_MBR_RoadWorkerExtensions_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _RoadWorkerExtensions_H_ */
#include <asn_internal.h>
