/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Map"
 * 	found in "Map.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_Section_H_
#define	_Section_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SectionId.h"
#include "LaneExList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Section */
typedef struct Section {
	SectionId_t	 secId;
	LaneExList_t	 lanes;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Section_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Section;
extern asn_SEQUENCE_specifics_t asn_SPC_Section_specs_1;
extern asn_TYPE_member_t asn_MBR_Section_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _Section_H_ */
#include <asn_internal.h>
