/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Map"
 * 	found in "Map.asn"
 * 	`asn1c -gen-PER`
 */

#include "Section.h"

asn_TYPE_member_t asn_MBR_Section_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Section, secId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SectionId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"secId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Section, lanes),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneExList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"lanes"
		},
};
static const ber_tlv_tag_t asn_DEF_Section_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Section_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* secId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* lanes */
};
asn_SEQUENCE_specifics_t asn_SPC_Section_specs_1 = {
	sizeof(struct Section),
	offsetof(struct Section, _asn_ctx),
	asn_MAP_Section_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Section = {
	"Section",
	"Section",
	&asn_OP_SEQUENCE,
	asn_DEF_Section_tags_1,
	sizeof(asn_DEF_Section_tags_1)
		/sizeof(asn_DEF_Section_tags_1[0]), /* 1 */
	asn_DEF_Section_tags_1,	/* Same as above */
	sizeof(asn_DEF_Section_tags_1)
		/sizeof(asn_DEF_Section_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Section_1,
	2,	/* Elements count */
	&asn_SPC_Section_specs_1	/* Additional specs */
};

