/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Map"
 * 	found in "Map.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_SectionId_H_
#define	_SectionId_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SectionId */
typedef long	 SectionId_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SectionId_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SectionId;
asn_struct_free_f SectionId_free;
asn_struct_print_f SectionId_print;
asn_constr_check_f SectionId_constraint;
ber_type_decoder_f SectionId_decode_ber;
der_type_encoder_f SectionId_encode_der;
xer_type_decoder_f SectionId_decode_xer;
xer_type_encoder_f SectionId_encode_xer;
oer_type_decoder_f SectionId_decode_oer;
oer_type_encoder_f SectionId_encode_oer;
per_type_decoder_f SectionId_decode_uper;
per_type_encoder_f SectionId_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SectionId_H_ */
#include <asn_internal.h>
