/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SensorSharing"
 * 	found in "SensorSharing.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_SensorSharingMsg_H_
#define	_SensorSharingMsg_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MsgCount.h"
#include <OCTET_STRING.h>
#include "EquipmentType.h"
#include "DSecond.h"
#include "Position3D.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DetectedRegion;
struct DetectedPTCList;
struct DetectedObstacleList;
struct RTEList;

/* SensorSharingMsg */
typedef struct SensorSharingMsg {
	MsgCount_t	 msgCnt;
	OCTET_STRING_t	 id;
	EquipmentType_t	 equipmentType;
	DSecond_t	 secMark;
	Position3D_t	 sensorPos;
	struct DetectedRegion	*detectedRegion	/* OPTIONAL */;
	struct DetectedPTCList	*participants	/* OPTIONAL */;
	struct DetectedObstacleList	*obstacles	/* OPTIONAL */;
	struct RTEList	*rtes	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SensorSharingMsg_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SensorSharingMsg;
extern asn_SEQUENCE_specifics_t asn_SPC_SensorSharingMsg_specs_1;
extern asn_TYPE_member_t asn_MBR_SensorSharingMsg_1[9];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DetectedRegion.h"
#include "DetectedPTCList.h"
#include "DetectedObstacleList.h"
#include "RTEList.h"

#endif	/* _SensorSharingMsg_H_ */
#include <asn_internal.h>
