/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Map"
 * 	found in "Map.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_STPointList_H_
#define	_STPointList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ST_Point;

/* STPointList */
typedef struct STPointList {
	A_SEQUENCE_OF(struct ST_Point) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} STPointList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_STPointList;
extern asn_SET_OF_specifics_t asn_SPC_STPointList_specs_1;
extern asn_TYPE_member_t asn_MBR_STPointList_1[1];
extern asn_per_constraints_t asn_PER_type_STPointList_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ST-Point.h"

#endif	/* _STPointList_H_ */
#include <asn_internal.h>
