/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VPM"
 * 	found in "VPM.asn"
 * 	`asn1c -gen-PER`
 */

#include "TollingNodeInfo.h"

asn_TYPE_member_t asn_MBR_TollingNodeInfo_1[] = {
	{ ATF_POINTER, 4, offsetof(struct TollingNodeInfo, id),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_StationOrGantryId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"id"
		},
	{ ATF_POINTER, 3, offsetof(struct TollingNodeInfo, pos),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Position3D,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pos"
		},
	{ ATF_POINTER, 2, offsetof(struct TollingNodeInfo, tollingNodeType),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TollingNodeType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tollingNodeType"
		},
	{ ATF_POINTER, 1, offsetof(struct TollingNodeInfo, tollingDirection),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TollingDirection,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tollingDirection"
		},
};
static const int asn_MAP_TollingNodeInfo_oms_1[] = { 0, 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_TollingNodeInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TollingNodeInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* id */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* pos */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* tollingNodeType */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* tollingDirection */
};
asn_SEQUENCE_specifics_t asn_SPC_TollingNodeInfo_specs_1 = {
	sizeof(struct TollingNodeInfo),
	offsetof(struct TollingNodeInfo, _asn_ctx),
	asn_MAP_TollingNodeInfo_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_TollingNodeInfo_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_TollingNodeInfo = {
	"TollingNodeInfo",
	"TollingNodeInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_TollingNodeInfo_tags_1,
	sizeof(asn_DEF_TollingNodeInfo_tags_1)
		/sizeof(asn_DEF_TollingNodeInfo_tags_1[0]), /* 1 */
	asn_DEF_TollingNodeInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_TollingNodeInfo_tags_1)
		/sizeof(asn_DEF_TollingNodeInfo_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_TollingNodeInfo_1,
	4,	/* Elements count */
	&asn_SPC_TollingNodeInfo_specs_1	/* Additional specs */
};

