/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VPM"
 * 	found in "VPM.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_TollingDirection_H_
#define	_TollingDirection_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TollingDirection {
	TollingDirection_north	= 0,
	TollingDirection_northeast	= 1,
	TollingDirection_east	= 2,
	TollingDirection_southeast	= 3,
	TollingDirection_south	= 4,
	TollingDirection_southwest	= 5,
	TollingDirection_west	= 6,
	TollingDirection_northwest	= 7
	/*
	 * Enumeration is extensible
	 */
} e_TollingDirection;

/* TollingDirection */
typedef long	 TollingDirection_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TollingDirection_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TollingDirection;
extern const asn_INTEGER_specifics_t asn_SPC_TollingDirection_specs_1;
asn_struct_free_f TollingDirection_free;
asn_struct_print_f TollingDirection_print;
asn_constr_check_f TollingDirection_constraint;
ber_type_decoder_f TollingDirection_decode_ber;
der_type_encoder_f TollingDirection_encode_der;
xer_type_decoder_f TollingDirection_decode_xer;
xer_type_encoder_f TollingDirection_encode_xer;
oer_type_decoder_f TollingDirection_decode_oer;
oer_type_encoder_f TollingDirection_encode_oer;
per_type_decoder_f TollingDirection_decode_uper;
per_type_encoder_f TollingDirection_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TollingDirection_H_ */
#include <asn_internal.h>
