/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VPM"
 * 	found in "VPM.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_TollingNodeType_H_
#define	_TollingNodeType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TollingNodeType {
	TollingNodeType_entranceStation	= 0,
	TollingNodeType_exitStation	= 1,
	TollingNodeType_entranceAndExitStation	= 2,
	TollingNodeType_gantry	= 3
	/*
	 * Enumeration is extensible
	 */
} e_TollingNodeType;

/* TollingNodeType */
typedef long	 TollingNodeType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TollingNodeType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TollingNodeType;
extern const asn_INTEGER_specifics_t asn_SPC_TollingNodeType_specs_1;
asn_struct_free_f TollingNodeType_free;
asn_struct_print_f TollingNodeType_print;
asn_constr_check_f TollingNodeType_constraint;
ber_type_decoder_f TollingNodeType_decode_ber;
der_type_encoder_f TollingNodeType_encode_der;
xer_type_decoder_f TollingNodeType_decode_xer;
xer_type_encoder_f TollingNodeType_encode_xer;
oer_type_decoder_f TollingNodeType_decode_oer;
oer_type_encoder_f TollingNodeType_encode_oer;
per_type_decoder_f TollingNodeType_decode_uper;
per_type_encoder_f TollingNodeType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TollingNodeType_H_ */
#include <asn_internal.h>
