/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VPM"
 * 	found in "VPM.asn"
 * 	`asn1c -gen-PER`
 */

#include "TollInfo.h"

static int
memb_price_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 424967295)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_tollRoad_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 2 && size <= 256)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_tollRoad_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(2..256)) */};
static asn_per_constraints_t asn_PER_type_tollRoad_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 8,  8,  2,  256 }	/* (SIZE(2..256)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_price_constr_2 CC_NOTUSED = {
	{ 4, 1 }	/* (0..424967295) */,
	-1};
static asn_per_constraints_t asn_PER_memb_price_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 29, -1,  0,  424967295 }	/* (0..424967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_tollRoad_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(2..256)) */};
static asn_per_constraints_t asn_PER_memb_tollRoad_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 8,  8,  2,  256 }	/* (SIZE(2..256)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_tollRoad_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_NodeReferenceID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_tollRoad_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_tollRoad_specs_5 = {
	sizeof(struct tollRoad),
	offsetof(struct tollRoad, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_tollRoad_5 = {
	"tollRoad",
	"tollRoad",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_tollRoad_tags_5,
	sizeof(asn_DEF_tollRoad_tags_5)
		/sizeof(asn_DEF_tollRoad_tags_5[0]) - 1, /* 1 */
	asn_DEF_tollRoad_tags_5,	/* Same as above */
	sizeof(asn_DEF_tollRoad_tags_5)
		/sizeof(asn_DEF_tollRoad_tags_5[0]), /* 2 */
	{ &asn_OER_type_tollRoad_constr_5, &asn_PER_type_tollRoad_constr_5, SEQUENCE_OF_constraint },
	asn_MBR_tollRoad_5,
	1,	/* Single element */
	&asn_SPC_tollRoad_specs_5	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_TollInfo_1[] = {
	{ ATF_POINTER, 7, offsetof(struct TollInfo, price),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_price_constr_2, &asn_PER_memb_price_constr_2,  memb_price_constraint_1 },
		0, 0, /* No default value */
		"price"
		},
	{ ATF_POINTER, 6, offsetof(struct TollInfo, entrancePos),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PositionOffsetLLV,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"entrancePos"
		},
	{ ATF_POINTER, 5, offsetof(struct TollInfo, exitPos),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PositionOffsetLLV,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"exitPos"
		},
	{ ATF_POINTER, 4, offsetof(struct TollInfo, tollRoad),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_tollRoad_5,
		0,
		{ &asn_OER_memb_tollRoad_constr_5, &asn_PER_memb_tollRoad_constr_5,  memb_tollRoad_constraint_1 },
		0, 0, /* No default value */
		"tollRoad"
		},
	{ ATF_POINTER, 3, offsetof(struct TollInfo, tollPath),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ReferencePath,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tollPath"
		},
	{ ATF_POINTER, 2, offsetof(struct TollInfo, timeBegin),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DDateTime,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"timeBegin"
		},
	{ ATF_POINTER, 1, offsetof(struct TollInfo, timeEnd),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DDateTime,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"timeEnd"
		},
};
static const int asn_MAP_TollInfo_oms_1[] = { 0, 1, 2, 3, 4, 5, 6 };
static const ber_tlv_tag_t asn_DEF_TollInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TollInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* price */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* entrancePos */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* exitPos */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* tollRoad */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* tollPath */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* timeBegin */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* timeEnd */
};
asn_SEQUENCE_specifics_t asn_SPC_TollInfo_specs_1 = {
	sizeof(struct TollInfo),
	offsetof(struct TollInfo, _asn_ctx),
	asn_MAP_TollInfo_tag2el_1,
	7,	/* Count of tags in the map */
	asn_MAP_TollInfo_oms_1,	/* Optional members */
	7, 0,	/* Root/Additions */
	7,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_TollInfo = {
	"TollInfo",
	"TollInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_TollInfo_tags_1,
	sizeof(asn_DEF_TollInfo_tags_1)
		/sizeof(asn_DEF_TollInfo_tags_1[0]), /* 1 */
	asn_DEF_TollInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_TollInfo_tags_1)
		/sizeof(asn_DEF_TollInfo_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_TollInfo_1,
	7,	/* Elements count */
	&asn_SPC_TollInfo_specs_1	/* Additional specs */
};

