/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VPM"
 * 	found in "VPM.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_TransPara_H_
#define	_TransPara_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TransPara */
typedef struct TransPara {
	OCTET_STRING_t	 transAmount;
	OCTET_STRING_t	 transType;
	OCTET_STRING_t	 terminalID;
	OCTET_STRING_t	 transSN;
	OCTET_STRING_t	 transTime;
	OCTET_STRING_t	 transStationID;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TransPara_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TransPara;
extern asn_SEQUENCE_specifics_t asn_SPC_TransPara_specs_1;
extern asn_TYPE_member_t asn_MBR_TransPara_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _TransPara_H_ */
#include <asn_internal.h>
