/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VIR"
 * 	found in "VIR.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_VehIntentionAndRequest_H_
#define	_VehIntentionAndRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MsgCount.h"
#include <OCTET_STRING.h>
#include "DSecond.h"
#include "Position3D.h"
#include "IARData.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VehIntentionAndRequest */
typedef struct VehIntentionAndRequest {
	MsgCount_t	 msgCnt;
	OCTET_STRING_t	 id;
	DSecond_t	 secMark;
	Position3D_t	 refPos;
	IARData_t	 intAndReq;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehIntentionAndRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehIntentionAndRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_VehIntentionAndRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_VehIntentionAndRequest_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _VehIntentionAndRequest_H_ */
#include <asn_internal.h>
