/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VPM"
 * 	found in "VPM.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_VehiclePaymentMessage_H_
#define	_VehiclePaymentMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MsgCount.h"
#include "RST.h"
#include "VSI.h"
#include "Action-Request.h"
#include "Action-Response.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum payment_PR {
	payment_PR_NOTHING,	/* No components present */
	payment_PR_initialzation_request,
	payment_PR_initialzation_response,
	payment_PR_action_request,
	payment_PR_action_response
	/* Extensions may appear below */
	
} payment_PR;

/* VehiclePaymentMessage */
typedef struct VehiclePaymentMessage {
	MsgCount_t	 msgCnt;
	struct payment {
		payment_PR present;
		union VehiclePaymentMessage__payment_u {
			RST_t	 initialzation_request;
			VSI_t	 initialzation_response;
			Action_Request_t	 action_request;
			Action_Response_t	 action_response;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} payment;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehiclePaymentMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehiclePaymentMessage;
extern asn_SEQUENCE_specifics_t asn_SPC_VehiclePaymentMessage_specs_1;
extern asn_TYPE_member_t asn_MBR_VehiclePaymentMessage_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _VehiclePaymentMessage_H_ */
#include <asn_internal.h>
