/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VPM"
 * 	found in "VPM.asn"
 * 	`asn1c -gen-PER`
 */

#include "VehiclePaymentMessage.h"

static asn_oer_constraints_t asn_OER_type_payment_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_payment_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  3 }	/* (0..3,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_payment_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct payment, choice.initialzation_request),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RST,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"initialzation-request"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct payment, choice.initialzation_response),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VSI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"initialzation-response"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct payment, choice.action_request),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Action_Request,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"action-request"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct payment, choice.action_response),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Action_Response,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"action-response"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_payment_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* initialzation-request */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* initialzation-response */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* action-request */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* action-response */
};
static asn_CHOICE_specifics_t asn_SPC_payment_specs_3 = {
	sizeof(struct payment),
	offsetof(struct payment, _asn_ctx),
	offsetof(struct payment, present),
	sizeof(((struct payment *)0)->present),
	asn_MAP_payment_tag2el_3,
	4,	/* Count of tags in the map */
	0, 0,
	4	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_payment_3 = {
	"payment",
	"payment",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_payment_constr_3, &asn_PER_type_payment_constr_3, CHOICE_constraint },
	asn_MBR_payment_3,
	4,	/* Elements count */
	&asn_SPC_payment_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_VehiclePaymentMessage_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct VehiclePaymentMessage, msgCnt),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MsgCount,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"msgCnt"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct VehiclePaymentMessage, payment),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_payment_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"payment"
		},
};
static const ber_tlv_tag_t asn_DEF_VehiclePaymentMessage_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_VehiclePaymentMessage_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* msgCnt */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* payment */
};
asn_SEQUENCE_specifics_t asn_SPC_VehiclePaymentMessage_specs_1 = {
	sizeof(struct VehiclePaymentMessage),
	offsetof(struct VehiclePaymentMessage, _asn_ctx),
	asn_MAP_VehiclePaymentMessage_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_VehiclePaymentMessage = {
	"VehiclePaymentMessage",
	"VehiclePaymentMessage",
	&asn_OP_SEQUENCE,
	asn_DEF_VehiclePaymentMessage_tags_1,
	sizeof(asn_DEF_VehiclePaymentMessage_tags_1)
		/sizeof(asn_DEF_VehiclePaymentMessage_tags_1[0]), /* 1 */
	asn_DEF_VehiclePaymentMessage_tags_1,	/* Same as above */
	sizeof(asn_DEF_VehiclePaymentMessage_tags_1)
		/sizeof(asn_DEF_VehiclePaymentMessage_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_VehiclePaymentMessage_1,
	2,	/* Elements count */
	&asn_SPC_VehiclePaymentMessage_specs_1	/* Additional specs */
};

