/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VPM"
 * 	found in "VPM.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_VPApplicationList_H_
#define	_VPApplicationList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VPApplicationParameter;

/* VPApplicationList */
typedef struct VPApplicationList {
	A_SEQUENCE_OF(struct VPApplicationParameter) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VPApplicationList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VPApplicationList;
extern asn_SET_OF_specifics_t asn_SPC_VPApplicationList_specs_1;
extern asn_TYPE_member_t asn_MBR_VPApplicationList_1[1];
extern asn_per_constraints_t asn_PER_type_VPApplicationList_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VPApplicationParameter.h"

#endif	/* _VPApplicationList_H_ */
#include <asn_internal.h>
