APP_DIR := .
ASN_DIR := ./
MODULE_SOURCES=	\
	BasicSafetyMessage.c	\
	AccelerationSet4Way.c	\
	Acceleration.c	\
	VerticalAcceleration.c	\
	YawRate.c	\
	Speed.c	\
	Heading.c	\
	CoarseHeading.c	\
	SteeringWheelAngle.c	\
	MotionConfidenceSet.c	\
	HeadingConfidence.c	\
	SpeedConfidence.c	\
	SteeringWheelAngleConfidence.c	\
	Latitude.c	\
	Longitude.c	\
	Elevation.c	\
	PositionConfidenceSet.c	\
	PositionConfidence.c	\
	ElevationConfidence.c	\
	Position3D.c	\
	PositionOffsetLLV.c	\
	OffsetLL-B12.c	\
	OffsetLL-B14.c	\
	OffsetLL-B16.c	\
	OffsetLL-B18.c	\
	OffsetLL-B22.c	\
	OffsetLL-B24.c	\
	Position-LL-24B.c	\
	Position-LL-28B.c	\
	Position-LL-32B.c	\
	Position-LL-36B.c	\
	Position-LL-44B.c	\
	Position-LL-48B.c	\
	Position-LLmD-64b.c	\
	PositionOffsetLL.c	\
	VerticalOffset.c	\
	VertOffset-B07.c	\
	VertOffset-B08.c	\
	VertOffset-B09.c	\
	VertOffset-B10.c	\
	VertOffset-B11.c	\
	VertOffset-B12.c	\
	DSecond.c	\
	DYear.c	\
	DMonth.c	\
	DDay.c	\
	DHour.c	\
	DMinute.c	\
	DTimeOffset.c	\
	DDateTime.c	\
	MinuteOfTheYear.c	\
	TimeMark.c	\
	TimeOffset.c	\
	TimeConfidence.c	\
	MapData.c	\
	LaneList.c	\
	Lane.c	\
	LaneID.c	\
	LaneWidth.c	\
	ConnectsToList.c	\
	Connection.c	\
	ConnectingLane.c	\
	AllowedManeuvers.c	\
	LaneAttributes.c	\
	LaneSharing.c	\
	LaneTypeAttributes.c	\
	LaneAttributes-Vehicle.c	\
	LaneAttributes-Crosswalk.c	\
	LaneAttributes-Bike.c	\
	LaneAttributes-Sidewalk.c	\
	LaneAttributes-Barrier.c	\
	LaneAttributes-Striping.c	\
	LaneAttributes-TrackedVehicle.c	\
	LaneAttributes-Parking.c	\
	LinkList.c	\
	Link.c	\
	MovementList.c	\
	Movement.c	\
	NodeList.c	\
	Node.c	\
	DescriptiveName.c	\
	NodeReferenceID.c	\
	RoadRegulatorID.c	\
	NodeID.c	\
	PointList.c	\
	RoadPoint.c	\
	SpeedLimitList.c	\
	RegulatorySpeedLimit.c	\
	SpeedLimitType.c	\
	MessageFrame.c	\
	MsgCount.c	\
	RoadSideInformation.c	\
	PathPointList.c	\
	Radius.c	\
	AlertType.c	\
	Priority.c	\
	RoadsideSafetyMessage.c	\
	ParticipantList.c	\
	ParticipantData.c	\
	ParticipantType.c	\
	SourceType.c	\
	SPAT.c	\
	IntersectionStateList.c	\
	IntersectionState.c	\
	IntersectionStatusObject.c	\
	PhaseList.c	\
	Phase.c	\
	PhaseStateList.c	\
	PhaseState.c	\
	LightState.c	\
	TimeChangeDetails.c	\
	PhaseID.c	\
	BrakeSystemStatus.c	\
	BrakePedalStatus.c	\
	BrakeAppliedStatus.c	\
	BrakeBoostApplied.c	\
	TractionControlStatus.c	\
	AntiLockBrakeStatus.c	\
	StabilityControlStatus.c	\
	AuxiliaryBrakeStatus.c	\
	VehicleClassification.c	\
	BasicVehicleClass.c	\
	VehicleSafetyExtensions.c	\
	PathHistory.c	\
	FullPositionVector.c	\
	GNSSstatus.c	\
	PathHistoryPointList.c	\
	PathHistoryPoint.c	\
	PathPrediction.c	\
	Confidence.c	\
	RadiusOfCurvature.c	\
	VehicleSize.c	\
	VehicleWidth.c	\
	VehicleLength.c	\
	VehicleHeight.c	\
	TransmissionState.c	\
	VehicleEventFlags.c	\
	ExteriorLights.c

MODULE_HEADERS=	\
	BasicSafetyMessage.h	\
	AccelerationSet4Way.h	\
	Acceleration.h	\
	VerticalAcceleration.h	\
	YawRate.h	\
	Speed.h	\
	Heading.h	\
	CoarseHeading.h	\
	SteeringWheelAngle.h	\
	MotionConfidenceSet.h	\
	HeadingConfidence.h	\
	SpeedConfidence.h	\
	SteeringWheelAngleConfidence.h	\
	Latitude.h	\
	Longitude.h	\
	Elevation.h	\
	PositionConfidenceSet.h	\
	PositionConfidence.h	\
	ElevationConfidence.h	\
	Position3D.h	\
	PositionOffsetLLV.h	\
	OffsetLL-B12.h	\
	OffsetLL-B14.h	\
	OffsetLL-B16.h	\
	OffsetLL-B18.h	\
	OffsetLL-B22.h	\
	OffsetLL-B24.h	\
	Position-LL-24B.h	\
	Position-LL-28B.h	\
	Position-LL-32B.h	\
	Position-LL-36B.h	\
	Position-LL-44B.h	\
	Position-LL-48B.h	\
	Position-LLmD-64b.h	\
	PositionOffsetLL.h	\
	VerticalOffset.h	\
	VertOffset-B07.h	\
	VertOffset-B08.h	\
	VertOffset-B09.h	\
	VertOffset-B10.h	\
	VertOffset-B11.h	\
	VertOffset-B12.h	\
	DSecond.h	\
	DYear.h	\
	DMonth.h	\
	DDay.h	\
	DHour.h	\
	DMinute.h	\
	DTimeOffset.h	\
	DDateTime.h	\
	MinuteOfTheYear.h	\
	TimeMark.h	\
	TimeOffset.h	\
	TimeConfidence.h	\
	MapData.h	\
	LaneList.h	\
	Lane.h	\
	LaneID.h	\
	LaneWidth.h	\
	ConnectsToList.h	\
	Connection.h	\
	ConnectingLane.h	\
	AllowedManeuvers.h	\
	LaneAttributes.h	\
	LaneSharing.h	\
	LaneTypeAttributes.h	\
	LaneAttributes-Vehicle.h	\
	LaneAttributes-Crosswalk.h	\
	LaneAttributes-Bike.h	\
	LaneAttributes-Sidewalk.h	\
	LaneAttributes-Barrier.h	\
	LaneAttributes-Striping.h	\
	LaneAttributes-TrackedVehicle.h	\
	LaneAttributes-Parking.h	\
	LinkList.h	\
	Link.h	\
	MovementList.h	\
	Movement.h	\
	NodeList.h	\
	Node.h	\
	DescriptiveName.h	\
	NodeReferenceID.h	\
	RoadRegulatorID.h	\
	NodeID.h	\
	PointList.h	\
	RoadPoint.h	\
	SpeedLimitList.h	\
	RegulatorySpeedLimit.h	\
	SpeedLimitType.h	\
	MessageFrame.h	\
	MsgCount.h	\
	RoadSideInformation.h	\
	PathPointList.h	\
	Radius.h	\
	AlertType.h	\
	Priority.h	\
	RoadsideSafetyMessage.h	\
	ParticipantList.h	\
	ParticipantData.h	\
	ParticipantType.h	\
	SourceType.h	\
	SPAT.h	\
	IntersectionStateList.h	\
	IntersectionState.h	\
	IntersectionStatusObject.h	\
	PhaseList.h	\
	Phase.h	\
	PhaseStateList.h	\
	PhaseState.h	\
	LightState.h	\
	TimeChangeDetails.h	\
	PhaseID.h	\
	BrakeSystemStatus.h	\
	BrakePedalStatus.h	\
	BrakeAppliedStatus.h	\
	BrakeBoostApplied.h	\
	TractionControlStatus.h	\
	AntiLockBrakeStatus.h	\
	StabilityControlStatus.h	\
	AuxiliaryBrakeStatus.h	\
	VehicleClassification.h	\
	BasicVehicleClass.h	\
	VehicleSafetyExtensions.h	\
	PathHistory.h	\
	FullPositionVector.h	\
	GNSSstatus.h	\
	PathHistoryPointList.h	\
	PathHistoryPoint.h	\
	PathPrediction.h	\
	Confidence.h	\
	RadiusOfCurvature.h	\
	VehicleSize.h	\
	VehicleWidth.h	\
	VehicleLength.h	\
	VehicleHeight.h	\
	TransmissionState.h	\
	VehicleEventFlags.h	\
	ExteriorLights.h

MODULE_HEADERS+=OPEN_TYPE.h
MODULE_SOURCES+=OPEN_TYPE.c
MODULE_HEADERS+=constr_CHOICE.h
MODULE_HEADERS+=IA5String.h
MODULE_SOURCES+=IA5String.c
MODULE_HEADERS+=OCTET_STRING.h
MODULE_HEADERS+=INTEGER.h
MODULE_SOURCES+=INTEGER.c
MODULE_HEADERS+=NativeEnumerated.h
MODULE_SOURCES+=NativeEnumerated.c
MODULE_HEADERS+=NativeInteger.h
MODULE_SOURCES+=NativeInteger.c
MODULE_HEADERS+=asn_SEQUENCE_OF.h
MODULE_SOURCES+=asn_SEQUENCE_OF.c
MODULE_HEADERS+=asn_SET_OF.h
MODULE_SOURCES+=asn_SET_OF.c
MODULE_SOURCES+=constr_CHOICE.c
MODULE_HEADERS+=constr_SEQUENCE.h
MODULE_SOURCES+=constr_SEQUENCE.c
MODULE_HEADERS+=constr_SEQUENCE_OF.h
MODULE_SOURCES+=constr_SEQUENCE_OF.c
MODULE_HEADERS+=constr_SET_OF.h
MODULE_SOURCES+=constr_SET_OF.c
MODULE_HEADERS+=asn_application.h
MODULE_SOURCES+=asn_application.c
MODULE_HEADERS+=asn_ioc.h
MODULE_HEADERS+=asn_system.h
MODULE_HEADERS+=asn_codecs.h
MODULE_HEADERS+=asn_internal.h
MODULE_SOURCES+=asn_internal.c
MODULE_HEADERS+=asn_random_fill.h
MODULE_SOURCES+=asn_random_fill.c
MODULE_HEADERS+=asn_bit_data.h
MODULE_SOURCES+=asn_bit_data.c
MODULE_SOURCES+=OCTET_STRING.c
MODULE_HEADERS+=BIT_STRING.h
MODULE_SOURCES+=BIT_STRING.c
MODULE_SOURCES+=asn_codecs_prim.c
MODULE_HEADERS+=asn_codecs_prim.h
MODULE_HEADERS+=ber_tlv_length.h
MODULE_SOURCES+=ber_tlv_length.c
MODULE_HEADERS+=ber_tlv_tag.h
MODULE_SOURCES+=ber_tlv_tag.c
MODULE_HEADERS+=ber_decoder.h
MODULE_SOURCES+=ber_decoder.c
MODULE_HEADERS+=der_encoder.h
MODULE_SOURCES+=der_encoder.c
MODULE_HEADERS+=constr_TYPE.h
MODULE_SOURCES+=constr_TYPE.c
MODULE_HEADERS+=constraints.h
MODULE_SOURCES+=constraints.c
MODULE_HEADERS+=xer_support.h
MODULE_SOURCES+=xer_support.c
MODULE_HEADERS+=xer_decoder.h
MODULE_SOURCES+=xer_decoder.c
MODULE_HEADERS+=xer_encoder.h
MODULE_SOURCES+=xer_encoder.c
MODULE_HEADERS+=per_support.h
MODULE_SOURCES+=per_support.c
MODULE_HEADERS+=per_decoder.h
MODULE_SOURCES+=per_decoder.c
MODULE_HEADERS+=per_encoder.h
MODULE_SOURCES+=per_encoder.c
MODULE_HEADERS+=per_opentype.h
MODULE_SOURCES+=per_opentype.c
MODULE_HEADERS+=oer_decoder.h
MODULE_HEADERS+=oer_encoder.h
MODULE_HEADERS+=oer_support.h
MODULE_SOURCES+=oer_decoder.c
MODULE_SOURCES+=oer_encoder.c
MODULE_SOURCES+=oer_support.c
MODULE_SOURCES+=OPEN_TYPE_oer.c
MODULE_SOURCES+=INTEGER_oer.c
MODULE_SOURCES+=BIT_STRING_oer.c
MODULE_SOURCES+=OCTET_STRING_oer.c
MODULE_SOURCES+=NativeInteger_oer.c
MODULE_SOURCES+=NativeEnumerated_oer.c
MODULE_SOURCES+=constr_CHOICE_oer.c
MODULE_SOURCES+=constr_SEQUENCE_oer.c
MODULE_SOURCES+=constr_SET_OF_oer.c





# This file may be used as an input for make(3)
# Remove the lines below to convert it into a pure .am file
TARGET = libmsgframe.so

EXTRA_CFLAGS += -I $(ASN_DIR)

OBJS := ${MODULE_SOURCES:.c=.o}

################################################################################
# Build Rules
################################################################################
CC := $(CROSS_COMPILE)gcc

all: $(TARGET)

$(TARGET): ${OBJS}
	$(CC) -shared $(CFLAGS) -o $(TARGET) ${OBJS} ${LDFLAGS}

.SUFFIXES:
.SUFFIXES: .c .o

.c.o:
	$(CC) $(CFLAGS) -fPIC -c $< -o $@ $(EXTRA_CFLAGS)
clean:
	rm -f $(TARGET)
	rm -f $(OBJS)
	find ./ -name "*.o" |xargs rm -rf
	find ./ -name "*.d" |xargs rm -rf
