/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSI"
 * 	found in "RSI.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_RoadSideInformation_H_
#define	_RoadSideInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MsgCount.h"
#include "MinuteOfTheYear.h"
#include <OCTET_STRING.h>
#include <NativeInteger.h>
#include "AlertType.h"
#include <IA5String.h>
#include "Priority.h"
#include "Position3D.h"
#include "PathPointList.h"
#include "Radius.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RoadSideInformation */
typedef struct RoadSideInformation {
	MsgCount_t	 msgCnt;
	MinuteOfTheYear_t	*timeStamp	/* OPTIONAL */;
	OCTET_STRING_t	 id;
	long	 rsiId;
	AlertType_t	 alertType;
	IA5String_t	*description	/* OPTIONAL */;
	Priority_t	*priority	/* OPTIONAL */;
	Position3D_t	 refPos;
	PathPointList_t	 alertPath;
	Radius_t	 alertRadius;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RoadSideInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RoadSideInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_RoadSideInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_RoadSideInformation_1[10];

#ifdef __cplusplus
}
#endif

#endif	/* _RoadSideInformation_H_ */
#include <asn_internal.h>
