/*
 * Generated by gdbus-codegen 2.56.4. DO NOT EDIT.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from.
 */

#ifndef __V2XOBU_GENERATED_H__
#define __V2XOBU_GENERATED_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for dbus.obu.v2x */

#define V2X_OBU_TYPE_V2X (v2x_obu_v2x_get_type ())
#define V2X_OBU_V2X(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), V2X_OBU_TYPE_V2X, V2xOBUV2x))
#define V2X_OBU_IS_V2X(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), V2X_OBU_TYPE_V2X))
#define V2X_OBU_V2X_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), V2X_OBU_TYPE_V2X, V2xOBUV2xIface))

struct _V2xOBUV2x;
typedef struct _V2xOBUV2x V2xOBUV2x;
typedef struct _V2xOBUV2xIface V2xOBUV2xIface;

struct _V2xOBUV2xIface
{
  GTypeInterface parent_iface;

  void (*v2x_srv_config_rs) (
    V2xOBUV2x *object,
    GVariant *arg_DataBuf,
    gint arg_length);

  void (*v2x_srv_fault_push) (
    V2xOBUV2x *object,
    GVariant *arg_DataBuf,
    gint arg_length);

  void (*v2x_srv_msg) (
    V2xOBUV2x *object,
    GVariant *arg_DataBuf,
    gint arg_length);

  void (*v2x_srv_state) (
    V2xOBUV2x *object,
    GVariant *arg_DataBuf,
    gint arg_length);

};

GType v2x_obu_v2x_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *v2x_obu_v2x_interface_info (void);
guint v2x_obu_v2x_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus signal emissions functions: */
void v2x_obu_v2x_emit_v2x_srv_msg (
    V2xOBUV2x *object,
    GVariant *arg_DataBuf,
    gint arg_length);

void v2x_obu_v2x_emit_v2x_srv_state (
    V2xOBUV2x *object,
    GVariant *arg_DataBuf,
    gint arg_length);

void v2x_obu_v2x_emit_v2x_srv_fault_push (
    V2xOBUV2x *object,
    GVariant *arg_DataBuf,
    gint arg_length);

void v2x_obu_v2x_emit_v2x_srv_config_rs (
    V2xOBUV2x *object,
    GVariant *arg_DataBuf,
    gint arg_length);



/* ---- */

#define V2X_OBU_TYPE_V2X_PROXY (v2x_obu_v2x_proxy_get_type ())
#define V2X_OBU_V2X_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), V2X_OBU_TYPE_V2X_PROXY, V2xOBUV2xProxy))
#define V2X_OBU_V2X_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), V2X_OBU_TYPE_V2X_PROXY, V2xOBUV2xProxyClass))
#define V2X_OBU_V2X_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), V2X_OBU_TYPE_V2X_PROXY, V2xOBUV2xProxyClass))
#define V2X_OBU_IS_V2X_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), V2X_OBU_TYPE_V2X_PROXY))
#define V2X_OBU_IS_V2X_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), V2X_OBU_TYPE_V2X_PROXY))

typedef struct _V2xOBUV2xProxy V2xOBUV2xProxy;
typedef struct _V2xOBUV2xProxyClass V2xOBUV2xProxyClass;
typedef struct _V2xOBUV2xProxyPrivate V2xOBUV2xProxyPrivate;

struct _V2xOBUV2xProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  V2xOBUV2xProxyPrivate *priv;
};

struct _V2xOBUV2xProxyClass
{
  GDBusProxyClass parent_class;
};

GType v2x_obu_v2x_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (V2xOBUV2xProxy, g_object_unref)
#endif

void v2x_obu_v2x_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
V2xOBUV2x *v2x_obu_v2x_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
V2xOBUV2x *v2x_obu_v2x_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void v2x_obu_v2x_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
V2xOBUV2x *v2x_obu_v2x_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
V2xOBUV2x *v2x_obu_v2x_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define V2X_OBU_TYPE_V2X_SKELETON (v2x_obu_v2x_skeleton_get_type ())
#define V2X_OBU_V2X_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), V2X_OBU_TYPE_V2X_SKELETON, V2xOBUV2xSkeleton))
#define V2X_OBU_V2X_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), V2X_OBU_TYPE_V2X_SKELETON, V2xOBUV2xSkeletonClass))
#define V2X_OBU_V2X_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), V2X_OBU_TYPE_V2X_SKELETON, V2xOBUV2xSkeletonClass))
#define V2X_OBU_IS_V2X_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), V2X_OBU_TYPE_V2X_SKELETON))
#define V2X_OBU_IS_V2X_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), V2X_OBU_TYPE_V2X_SKELETON))

typedef struct _V2xOBUV2xSkeleton V2xOBUV2xSkeleton;
typedef struct _V2xOBUV2xSkeletonClass V2xOBUV2xSkeletonClass;
typedef struct _V2xOBUV2xSkeletonPrivate V2xOBUV2xSkeletonPrivate;

struct _V2xOBUV2xSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  V2xOBUV2xSkeletonPrivate *priv;
};

struct _V2xOBUV2xSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType v2x_obu_v2x_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (V2xOBUV2xSkeleton, g_object_unref)
#endif

V2xOBUV2x *v2x_obu_v2x_skeleton_new (void);


/* ------------------------------------------------------------------------ */
/* Declarations for dbus.obu.app */

#define V2X_OBU_TYPE_APP (v2x_obu_app_get_type ())
#define V2X_OBU_APP(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), V2X_OBU_TYPE_APP, V2xOBUApp))
#define V2X_OBU_IS_APP(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), V2X_OBU_TYPE_APP))
#define V2X_OBU_APP_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), V2X_OBU_TYPE_APP, V2xOBUAppIface))

struct _V2xOBUApp;
typedef struct _V2xOBUApp V2xOBUApp;
typedef struct _V2xOBUAppIface V2xOBUAppIface;

struct _V2xOBUAppIface
{
  GTypeInterface parent_iface;

  void (*app_config_rs) (
    V2xOBUApp *object,
    GVariant *arg_DataBuf,
    gint arg_length);

  void (*app_fault_push) (
    V2xOBUApp *object,
    GVariant *arg_DataBuf,
    gint arg_length);

  void (*app_result_act_safe) (
    V2xOBUApp *object,
    GVariant *arg_DataBuf,
    gint arg_length);

  void (*app_result_spd_guide) (
    V2xOBUApp *object,
    GVariant *arg_DataBuf,
    gint arg_length);

  void (*app_result_trfc_remind) (
    V2xOBUApp *object,
    GVariant *arg_DataBuf,
    gint arg_length);

};

GType v2x_obu_app_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *v2x_obu_app_interface_info (void);
guint v2x_obu_app_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus signal emissions functions: */
void v2x_obu_app_emit_app_result_act_safe (
    V2xOBUApp *object,
    GVariant *arg_DataBuf,
    gint arg_length);

void v2x_obu_app_emit_app_result_trfc_remind (
    V2xOBUApp *object,
    GVariant *arg_DataBuf,
    gint arg_length);

void v2x_obu_app_emit_app_result_spd_guide (
    V2xOBUApp *object,
    GVariant *arg_DataBuf,
    gint arg_length);

void v2x_obu_app_emit_app_config_rs (
    V2xOBUApp *object,
    GVariant *arg_DataBuf,
    gint arg_length);

void v2x_obu_app_emit_app_fault_push (
    V2xOBUApp *object,
    GVariant *arg_DataBuf,
    gint arg_length);



/* ---- */

#define V2X_OBU_TYPE_APP_PROXY (v2x_obu_app_proxy_get_type ())
#define V2X_OBU_APP_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), V2X_OBU_TYPE_APP_PROXY, V2xOBUAppProxy))
#define V2X_OBU_APP_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), V2X_OBU_TYPE_APP_PROXY, V2xOBUAppProxyClass))
#define V2X_OBU_APP_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), V2X_OBU_TYPE_APP_PROXY, V2xOBUAppProxyClass))
#define V2X_OBU_IS_APP_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), V2X_OBU_TYPE_APP_PROXY))
#define V2X_OBU_IS_APP_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), V2X_OBU_TYPE_APP_PROXY))

typedef struct _V2xOBUAppProxy V2xOBUAppProxy;
typedef struct _V2xOBUAppProxyClass V2xOBUAppProxyClass;
typedef struct _V2xOBUAppProxyPrivate V2xOBUAppProxyPrivate;

struct _V2xOBUAppProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  V2xOBUAppProxyPrivate *priv;
};

struct _V2xOBUAppProxyClass
{
  GDBusProxyClass parent_class;
};

GType v2x_obu_app_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (V2xOBUAppProxy, g_object_unref)
#endif

void v2x_obu_app_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
V2xOBUApp *v2x_obu_app_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
V2xOBUApp *v2x_obu_app_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void v2x_obu_app_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
V2xOBUApp *v2x_obu_app_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
V2xOBUApp *v2x_obu_app_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define V2X_OBU_TYPE_APP_SKELETON (v2x_obu_app_skeleton_get_type ())
#define V2X_OBU_APP_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), V2X_OBU_TYPE_APP_SKELETON, V2xOBUAppSkeleton))
#define V2X_OBU_APP_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), V2X_OBU_TYPE_APP_SKELETON, V2xOBUAppSkeletonClass))
#define V2X_OBU_APP_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), V2X_OBU_TYPE_APP_SKELETON, V2xOBUAppSkeletonClass))
#define V2X_OBU_IS_APP_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), V2X_OBU_TYPE_APP_SKELETON))
#define V2X_OBU_IS_APP_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), V2X_OBU_TYPE_APP_SKELETON))

typedef struct _V2xOBUAppSkeleton V2xOBUAppSkeleton;
typedef struct _V2xOBUAppSkeletonClass V2xOBUAppSkeletonClass;
typedef struct _V2xOBUAppSkeletonPrivate V2xOBUAppSkeletonPrivate;

struct _V2xOBUAppSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  V2xOBUAppSkeletonPrivate *priv;
};

struct _V2xOBUAppSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType v2x_obu_app_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (V2xOBUAppSkeleton, g_object_unref)
#endif

V2xOBUApp *v2x_obu_app_skeleton_new (void);


/* ------------------------------------------------------------------------ */
/* Declarations for dbus.obu.vds */

#define V2X_OBU_TYPE_VDS (v2x_obu_vds_get_type ())
#define V2X_OBU_VDS(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), V2X_OBU_TYPE_VDS, V2xOBUVds))
#define V2X_OBU_IS_VDS(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), V2X_OBU_TYPE_VDS))
#define V2X_OBU_VDS_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), V2X_OBU_TYPE_VDS, V2xOBUVdsIface))

struct _V2xOBUVds;
typedef struct _V2xOBUVds V2xOBUVds;
typedef struct _V2xOBUVdsIface V2xOBUVdsIface;

struct _V2xOBUVdsIface
{
  GTypeInterface parent_iface;

  void (*mcu_fault_push) (
    V2xOBUVds *object,
    GVariant *arg_DataBuf,
    gint arg_length);

  void (*mcu_power_down_rq) (
    V2xOBUVds *object,
    GVariant *arg_DataBuf,
    gint arg_length);

  void (*vds_config_rs) (
    V2xOBUVds *object,
    GVariant *arg_DataBuf,
    gint arg_length);

  void (*vds_fault_push) (
    V2xOBUVds *object,
    GVariant *arg_DataBuf,
    gint arg_length);

  void (*vds_state_push) (
    V2xOBUVds *object,
    GVariant *arg_DataBuf,
    gint arg_length);

  void (*vds_veh_data) (
    V2xOBUVds *object,
    GVariant *arg_DataBuf,
    gint arg_length);

};

GType v2x_obu_vds_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *v2x_obu_vds_interface_info (void);
guint v2x_obu_vds_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus signal emissions functions: */
void v2x_obu_vds_emit_vds_veh_data (
    V2xOBUVds *object,
    GVariant *arg_DataBuf,
    gint arg_length);

void v2x_obu_vds_emit_vds_state_push (
    V2xOBUVds *object,
    GVariant *arg_DataBuf,
    gint arg_length);

void v2x_obu_vds_emit_vds_fault_push (
    V2xOBUVds *object,
    GVariant *arg_DataBuf,
    gint arg_length);

void v2x_obu_vds_emit_mcu_fault_push (
    V2xOBUVds *object,
    GVariant *arg_DataBuf,
    gint arg_length);

void v2x_obu_vds_emit_mcu_power_down_rq (
    V2xOBUVds *object,
    GVariant *arg_DataBuf,
    gint arg_length);

void v2x_obu_vds_emit_vds_config_rs (
    V2xOBUVds *object,
    GVariant *arg_DataBuf,
    gint arg_length);



/* ---- */

#define V2X_OBU_TYPE_VDS_PROXY (v2x_obu_vds_proxy_get_type ())
#define V2X_OBU_VDS_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), V2X_OBU_TYPE_VDS_PROXY, V2xOBUVdsProxy))
#define V2X_OBU_VDS_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), V2X_OBU_TYPE_VDS_PROXY, V2xOBUVdsProxyClass))
#define V2X_OBU_VDS_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), V2X_OBU_TYPE_VDS_PROXY, V2xOBUVdsProxyClass))
#define V2X_OBU_IS_VDS_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), V2X_OBU_TYPE_VDS_PROXY))
#define V2X_OBU_IS_VDS_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), V2X_OBU_TYPE_VDS_PROXY))

typedef struct _V2xOBUVdsProxy V2xOBUVdsProxy;
typedef struct _V2xOBUVdsProxyClass V2xOBUVdsProxyClass;
typedef struct _V2xOBUVdsProxyPrivate V2xOBUVdsProxyPrivate;

struct _V2xOBUVdsProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  V2xOBUVdsProxyPrivate *priv;
};

struct _V2xOBUVdsProxyClass
{
  GDBusProxyClass parent_class;
};

GType v2x_obu_vds_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (V2xOBUVdsProxy, g_object_unref)
#endif

void v2x_obu_vds_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
V2xOBUVds *v2x_obu_vds_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
V2xOBUVds *v2x_obu_vds_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void v2x_obu_vds_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
V2xOBUVds *v2x_obu_vds_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
V2xOBUVds *v2x_obu_vds_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define V2X_OBU_TYPE_VDS_SKELETON (v2x_obu_vds_skeleton_get_type ())
#define V2X_OBU_VDS_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), V2X_OBU_TYPE_VDS_SKELETON, V2xOBUVdsSkeleton))
#define V2X_OBU_VDS_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), V2X_OBU_TYPE_VDS_SKELETON, V2xOBUVdsSkeletonClass))
#define V2X_OBU_VDS_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), V2X_OBU_TYPE_VDS_SKELETON, V2xOBUVdsSkeletonClass))
#define V2X_OBU_IS_VDS_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), V2X_OBU_TYPE_VDS_SKELETON))
#define V2X_OBU_IS_VDS_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), V2X_OBU_TYPE_VDS_SKELETON))

typedef struct _V2xOBUVdsSkeleton V2xOBUVdsSkeleton;
typedef struct _V2xOBUVdsSkeletonClass V2xOBUVdsSkeletonClass;
typedef struct _V2xOBUVdsSkeletonPrivate V2xOBUVdsSkeletonPrivate;

struct _V2xOBUVdsSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  V2xOBUVdsSkeletonPrivate *priv;
};

struct _V2xOBUVdsSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType v2x_obu_vds_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (V2xOBUVdsSkeleton, g_object_unref)
#endif

V2xOBUVds *v2x_obu_vds_skeleton_new (void);


/* ------------------------------------------------------------------------ */
/* Declarations for dbus.obu.net */

#define V2X_OBU_TYPE_NET (v2x_obu_net_get_type ())
#define V2X_OBU_NET(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), V2X_OBU_TYPE_NET, V2xOBUNet))
#define V2X_OBU_IS_NET(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), V2X_OBU_TYPE_NET))
#define V2X_OBU_NET_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), V2X_OBU_TYPE_NET, V2xOBUNetIface))

struct _V2xOBUNet;
typedef struct _V2xOBUNet V2xOBUNet;
typedef struct _V2xOBUNetIface V2xOBUNetIface;

struct _V2xOBUNetIface
{
  GTypeInterface parent_iface;

  void (*net_config_rs) (
    V2xOBUNet *object,
    GVariant *arg_DataBuf,
    gint arg_length);

  void (*net_sim_can_data) (
    V2xOBUNet *object,
    GVariant *arg_DataBuf,
    gint arg_length);

  void (*net_status) (
    V2xOBUNet *object,
    GVariant *arg_DataBuf,
    gint arg_length);

};

GType v2x_obu_net_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *v2x_obu_net_interface_info (void);
guint v2x_obu_net_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus signal emissions functions: */
void v2x_obu_net_emit_net_sim_can_data (
    V2xOBUNet *object,
    GVariant *arg_DataBuf,
    gint arg_length);

void v2x_obu_net_emit_net_status (
    V2xOBUNet *object,
    GVariant *arg_DataBuf,
    gint arg_length);

void v2x_obu_net_emit_net_config_rs (
    V2xOBUNet *object,
    GVariant *arg_DataBuf,
    gint arg_length);



/* ---- */

#define V2X_OBU_TYPE_NET_PROXY (v2x_obu_net_proxy_get_type ())
#define V2X_OBU_NET_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), V2X_OBU_TYPE_NET_PROXY, V2xOBUNetProxy))
#define V2X_OBU_NET_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), V2X_OBU_TYPE_NET_PROXY, V2xOBUNetProxyClass))
#define V2X_OBU_NET_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), V2X_OBU_TYPE_NET_PROXY, V2xOBUNetProxyClass))
#define V2X_OBU_IS_NET_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), V2X_OBU_TYPE_NET_PROXY))
#define V2X_OBU_IS_NET_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), V2X_OBU_TYPE_NET_PROXY))

typedef struct _V2xOBUNetProxy V2xOBUNetProxy;
typedef struct _V2xOBUNetProxyClass V2xOBUNetProxyClass;
typedef struct _V2xOBUNetProxyPrivate V2xOBUNetProxyPrivate;

struct _V2xOBUNetProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  V2xOBUNetProxyPrivate *priv;
};

struct _V2xOBUNetProxyClass
{
  GDBusProxyClass parent_class;
};

GType v2x_obu_net_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (V2xOBUNetProxy, g_object_unref)
#endif

void v2x_obu_net_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
V2xOBUNet *v2x_obu_net_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
V2xOBUNet *v2x_obu_net_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void v2x_obu_net_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
V2xOBUNet *v2x_obu_net_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
V2xOBUNet *v2x_obu_net_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define V2X_OBU_TYPE_NET_SKELETON (v2x_obu_net_skeleton_get_type ())
#define V2X_OBU_NET_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), V2X_OBU_TYPE_NET_SKELETON, V2xOBUNetSkeleton))
#define V2X_OBU_NET_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), V2X_OBU_TYPE_NET_SKELETON, V2xOBUNetSkeletonClass))
#define V2X_OBU_NET_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), V2X_OBU_TYPE_NET_SKELETON, V2xOBUNetSkeletonClass))
#define V2X_OBU_IS_NET_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), V2X_OBU_TYPE_NET_SKELETON))
#define V2X_OBU_IS_NET_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), V2X_OBU_TYPE_NET_SKELETON))

typedef struct _V2xOBUNetSkeleton V2xOBUNetSkeleton;
typedef struct _V2xOBUNetSkeletonClass V2xOBUNetSkeletonClass;
typedef struct _V2xOBUNetSkeletonPrivate V2xOBUNetSkeletonPrivate;

struct _V2xOBUNetSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  V2xOBUNetSkeletonPrivate *priv;
};

struct _V2xOBUNetSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType v2x_obu_net_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (V2xOBUNetSkeleton, g_object_unref)
#endif

V2xOBUNet *v2x_obu_net_skeleton_new (void);


/* ------------------------------------------------------------------------ */
/* Declarations for dbus.obu.sys */

#define V2X_OBU_TYPE_SYS (v2x_obu_sys_get_type ())
#define V2X_OBU_SYS(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), V2X_OBU_TYPE_SYS, V2xOBUSys))
#define V2X_OBU_IS_SYS(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), V2X_OBU_TYPE_SYS))
#define V2X_OBU_SYS_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), V2X_OBU_TYPE_SYS, V2xOBUSysIface))

struct _V2xOBUSys;
typedef struct _V2xOBUSys V2xOBUSys;
typedef struct _V2xOBUSysIface V2xOBUSysIface;

struct _V2xOBUSysIface
{
  GTypeInterface parent_iface;

  void (*sys_config_rq) (
    V2xOBUSys *object,
    GVariant *arg_DataBuf,
    gint arg_length);

  void (*sys_mcu_power_down_rs) (
    V2xOBUSys *object,
    GVariant *arg_DataBuf,
    gint arg_length);

};

GType v2x_obu_sys_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *v2x_obu_sys_interface_info (void);
guint v2x_obu_sys_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus signal emissions functions: */
void v2x_obu_sys_emit_sys_config_rq (
    V2xOBUSys *object,
    GVariant *arg_DataBuf,
    gint arg_length);

void v2x_obu_sys_emit_sys_mcu_power_down_rs (
    V2xOBUSys *object,
    GVariant *arg_DataBuf,
    gint arg_length);



/* ---- */

#define V2X_OBU_TYPE_SYS_PROXY (v2x_obu_sys_proxy_get_type ())
#define V2X_OBU_SYS_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), V2X_OBU_TYPE_SYS_PROXY, V2xOBUSysProxy))
#define V2X_OBU_SYS_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), V2X_OBU_TYPE_SYS_PROXY, V2xOBUSysProxyClass))
#define V2X_OBU_SYS_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), V2X_OBU_TYPE_SYS_PROXY, V2xOBUSysProxyClass))
#define V2X_OBU_IS_SYS_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), V2X_OBU_TYPE_SYS_PROXY))
#define V2X_OBU_IS_SYS_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), V2X_OBU_TYPE_SYS_PROXY))

typedef struct _V2xOBUSysProxy V2xOBUSysProxy;
typedef struct _V2xOBUSysProxyClass V2xOBUSysProxyClass;
typedef struct _V2xOBUSysProxyPrivate V2xOBUSysProxyPrivate;

struct _V2xOBUSysProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  V2xOBUSysProxyPrivate *priv;
};

struct _V2xOBUSysProxyClass
{
  GDBusProxyClass parent_class;
};

GType v2x_obu_sys_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (V2xOBUSysProxy, g_object_unref)
#endif

void v2x_obu_sys_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
V2xOBUSys *v2x_obu_sys_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
V2xOBUSys *v2x_obu_sys_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void v2x_obu_sys_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
V2xOBUSys *v2x_obu_sys_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
V2xOBUSys *v2x_obu_sys_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define V2X_OBU_TYPE_SYS_SKELETON (v2x_obu_sys_skeleton_get_type ())
#define V2X_OBU_SYS_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), V2X_OBU_TYPE_SYS_SKELETON, V2xOBUSysSkeleton))
#define V2X_OBU_SYS_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), V2X_OBU_TYPE_SYS_SKELETON, V2xOBUSysSkeletonClass))
#define V2X_OBU_SYS_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), V2X_OBU_TYPE_SYS_SKELETON, V2xOBUSysSkeletonClass))
#define V2X_OBU_IS_SYS_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), V2X_OBU_TYPE_SYS_SKELETON))
#define V2X_OBU_IS_SYS_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), V2X_OBU_TYPE_SYS_SKELETON))

typedef struct _V2xOBUSysSkeleton V2xOBUSysSkeleton;
typedef struct _V2xOBUSysSkeletonClass V2xOBUSysSkeletonClass;
typedef struct _V2xOBUSysSkeletonPrivate V2xOBUSysSkeletonPrivate;

struct _V2xOBUSysSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  V2xOBUSysSkeletonPrivate *priv;
};

struct _V2xOBUSysSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType v2x_obu_sys_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (V2xOBUSysSkeleton, g_object_unref)
#endif

V2xOBUSys *v2x_obu_sys_skeleton_new (void);


G_END_DECLS

#endif /* __V2XOBU_GENERATED_H__ */
